version: 2

project_name: devup

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: devup
    main: ./cmd/devup
    binary: devup
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    env:
      - CGO_ENABLED=0

archives:
  - id: devup
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    files:
      - README.md

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: RajarshiParmar
    name: devup
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} {{.Tag}}"
